services:
  db:
    image: mysql:8.0
    container_name: finance-db-local
    restart: always
    environment:
      MYSQL_DATABASE: finance_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
